version: '3'

services:
    database:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
        ports: [5432]
    pgadmin:
        image: dpage/pgadmin4
        links:
          - database
        depends_on:
          - database
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: pwdpwd
        volumes:
          - pgadmin:/root/.pgadmin
        ports:
          - "5050:80"
volumes:
    database:
    pgadmin: